[tool.black]
line-length = 88
target-version = ['py310'] # Ajuster si nécessaire

[tool.ruff]
line-length = 88
select = ["E", "W", "F", "I", "UP", "PL", "PT"] # Exemple de règles
ignore = []
# Configuration spécifique pour FastAPI/Pydantic si nécessaire
# ... autres configurations ruff